const saudiCities = [
    { value: 'riyadh', label: 'Riyadh' },
    { value: 'jeddah', label: 'Jeddah' },
    { value: 'mecca', label: 'Mecca' },
    { value: 'medina', label: 'Medina' },
    { value: 'dammam', label: 'Dammam' },
    { value: 'tabuk', label: 'Tabuk' },
    { value: 'abha', label: 'Abha' },
    { value: 'jizan', label: 'Jizan' },
    { value: 'taif', label: 'Taif' },
    { value: 'khobar', label: 'Khobar' },
    { value: 'buraidah', label: 'Buraidah' },
    { value: 'najran', label: 'Najran' },
    { value: 'hafr al-batin', label: 'Hafr al-Batin' },
    { value: 'yanbu', label: 'Yanbu' },
    { value: 'al kharj', label: 'Al Kharj' },
    { value: 'hofuf', label: 'Hofuf' },
    { value: 'arar', label: 'Arar' },
    { value: 'al-bahah', label: 'Al-Bahah' },
    { value: 'umm al-qaar', label: 'Umm Al-Qaar' },
    { value: 'qurayyat', label: 'Qurayyat' },
    { value: 'dhahran', label: 'Dhahran' },
    { value: 'al hawiyah', label: 'Al Hawiyah' },
    { value: 'al qunfudhah', label: 'Al Qunfudhah' },
    { value: 'al jubail', label: 'Al Jubail' },
    { value: 'al wajh', label: 'Al Wajh' },
    { value: 'turayf', label: 'Turayf' },
    { value: 'almajmaah', label: 'Al-Majmaah' },
    { value: 'sharurah', label: 'Sharurah' },
    { value: 'al qatif', label: 'Al Qatif' },
    { value: 'al-khafji', label: 'Al-Khafji' },
    { value: 'as-sulayyil', label: 'As-Sulayyil' },
    { value: 'al-mubarraz', label: 'Al-Mubarraz' },
    { value: 'sakakah', label: 'Sakakah' },
    { value: 'al hufuf', label: 'Al Hufuf' },
    { value: 'sayhat', label: 'Sayhat' },
    { value: 'al-bukayriyah', label: 'Al-Bukayriyah' },
    { value: 'afif', label: 'Afif' },
    { value: 'abu arish', label: 'Abu Arish' },
    { value: 'safwa', label: 'Safwa' },
    { value: 'bisha', label: 'Bisha' },
    { value: 'alqurayat', label: 'Alqurayat' }
];