export const cities = [
  "--Please Select--",
  "Riyadh",
  "Jeddah",
  "Makkah",
  "Madinah",
  "Dammam",
  "Taif",
  "Buraidah",
  "Khobar",
  "Tabuk",
  "Abha",
  "Jazan",
  "Najran",
  "Al-Ahsa",
  "Al-Kharj",
  "Hail",
  "Arar",
  "Yanbu",
  "Jubail",
  "Al-Qatif",
  "Hafr Al-Batin",
  "Sakaka",
  "Al-Jawf",
  "Qurayyat",
  "Dhahran",
  "Al-Baha",
  "Safwa",
  "Ras Tanura",
  "Qatif",
  "Ad Diriyah",
  "Al-Qunfudhah",
  "Al-Ula",
  "As Sulayyil",
  "Al-Wajh",
  "Badr",
  "Baljurashi",
  "Duba",
  "Dumat Al-Jandal",
  "Ha'il",
  "Jizan",
  "Khafji",
  "Rabigh",
  "Rafha",
  "Sharurah",
  "Turaif",
  "Udhailiyah",
  "Unayzah",
  "Wadi Al-Dawasir",
  "Al Artaweeiyah",
  "Al-Aridhah",
  "Al-Badai",
  "Al-Bahah",
  "Al-Ghat",
  "Al-Hada",
  "Al-Hazm",
  "Al-Khafji",
  "Al-Khubar",
  "Al-Lith",
  "Al-Majma'ah",
  "Al-Mikhwah",
  "Al-Mubarraz",
  "Al-Munawwarah",
  "Al-Omran",
  "Al-Qassim",
  "Al-Rass",
  "Al-Ruwais",
  "Al-Thadiq",
  "Al-Wajeha Al-Bahriya",
  "Ar Rass",
  "At Taraf",
  "Badr Al-Janoub",
  "Bisha",
  "Buqayq",
  "Daelim",
  "Dammam Al Khobar Highway",
  "Darmaa",
  "Dhurma",
  "Dhurma Sudair Road",
  "Dubai",
  "Dumat Al-Djandal",
  "Dwadmi",
  "El Hadaba",
  "Gassim",
  "Gurayat",
  "Hafeet",
  "Hafr Al-Ataishah",
  "Hofuf",
  "Houtat Sudair",
  "Jabal Sayid",
  "Jeddah Makkah Highway",
  "Jizan Economic City",
  "Khamis Mushayt",
  "King Abdullah Economic City",
  "King Fahd International Airport",
  "Kumai",
  "Layla",
  "Majma'ah",
  "Marat",
  "Nafud",
  "Oyoun Al-Jawa",
  "Qaisumah",
  "Qal'at Bishah",
  "Qatif Al-Jisr",
  "Rabegh",
  "Ras Al-Khair",
  "Ras Al-Khaimah",
  "Ras Tanoura Port",
];
