export const options = [
  'Accounting',
  'Aerospace Engineering',
  'Anthropology',
  'Architecture',
  'Art History',
  'Artificial Intelligence',
  'Biology',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Communications',
  'Computer Science',
  'Criminal Justice',
  'Cybersecurity',
  'Data Science',
  'Digital Media',
  'Economics',
  'Education',
  'Electrical Engineering',
  'English',
  'Environmental Science',
  'Finance',
  'Fine Arts',
  'Game Design',
  'Geology',
  'Graphic Design',
  'History',
  'Information Systems',
  'Information Technology',
  'International Relations',
  'Journalism',
  'Law',
  'Linguistics',
  'Management',
  'Marketing',
  'Mathematics',
  'Mechanical Engineering',
  'Medicine',
  'Music',
  'Network Administration',
  'Nursing',
  'Philosophy',
  'Physics',
  'Political Science',
  'Psychology',
  'Public Health',
  'Public Relations',
  'Religious Studies',
  'Robotics',
  'Social Work',
  'Sociology',
  'Software Development',
  'Software Engineering',
  'Sports Science',
  'Statistics',
  'Theater',
  'Urban Planning',
  'Web Development',
  'Women\'s Studies'
];
