export const skillsList = [
    'Accounting',
    'Administration',
    'Agile',
    'Analysis',
    'Analytics',
    'Android',
    'AngularJS',
    'Artificial Intelligence',
    'ASP.NET',
    'AWS',
    'Backend Development',
    'Big Data',
    'Blogging',
    'Budgeting',
    'Business Development',
    'C#',
    'C++',
    'Change Management',
    'Cloud Computing',
    'Coaching',
    'Coding',
    'Communication',
    'Compensation',
    'Compliance',
    'Consulting',
    'Content Marketing',
    'Content Writing',
    'Copywriting',
    'Counseling',
    'Creative Writing',
    'CRM',
    'CSS',
    'Customer Service',
    'Data Analysis',
    'Data Entry',
    'Data Management',
    'Data Mining',
    'Data Science',
    'Database Administration',
    'Design',
    'Digital Marketing',
    'E-commerce',
    'Editing',
    'Education',
    'Email Marketing',
    'Employee Relations',
    'Engineering',
    'Enterprise Software',
    'Entrepreneurship',
    'Event Planning',
    'Excel',
    'Facebook Ads',
    'Finance',
    'Financial Analysis',
    'Forecasting',
    'Front End Development',
    'Fundraising',
    'Google Analytics',
    'Graphic Design',
    'HTML',
    'Human Resources',
    'Illustration',
    'Inbound Marketing',
    'Information Technology',
    'Insurance',
    'Interior Design',
    'International Sales',
    'Inventory Management',
    'Investment Banking',
    'iOS',
    'Java',
    'JavaScript',
    'Jira',
    'Leadership',
    'Lean Six Sigma',
    'Legal',
    'Logistics',
    'Machine Learning',
    'Management',
    'Market Analysis',
    'Market Research',
    'Marketing',
    'Media Relations',
    'Microsoft Office',
    'Mobile Development',
    'MySQL',
    'Negotiation',
    'Network Administration',
    'Networking',
    'Node.js',
    'Operations Management',
    'Organizational Development',
    'Outbound Marketing',
    'Payroll',
    'Performance Management',
    'Perl',
    'PHP',
    'Photoshop',
    'Pinterest Ads',
    'Planning',
    'Policies',
    'PowerPoint',
    'Presentations',
    'Process Improvement',
    'Product Development',
    'Product Management',
    'Program Management',
    'Project Management',
    'Proofreading',
    'Public Relations',
    'Python',
    'Quality Assurance',
    'React',
    'Recruiting',
    'Relationship Management',
    'Reporting',
    'Research',
    'REST',
    'Ruby',
    'Sales',
    'Salesforce',
    'SAP',
    'Scheduling',
    'Search Engine Marketing',
    'Search Engine Optimization',
    'Security',
    'SEO',
    'Social Media',
    'Social Media Advertising',
    'Software Development',
    'Software Engineering',
    'Software Testing',
    'Spanish',
    'SQL',
    'Statistics',
    'Strategic Planning',
    'Supply Chain Management',
    'Swift',
    'Tableau',
    'Team Building',
    'Teamwork',
    'Technical Writing',
    'Telecommunications',
    'Time Management',
    'Training',
    'Troubleshooting',
    'UI Design',
    'UX Design',
    'Vendor Management',
    'Video Editing',
    'Virtualization',
    'Visual'
];
  