export const skillsList = [
    { value: 'Communication', label: 'Communication' },
    { value: 'Leadership', label: 'Leadership' },
    { value: 'Teamwork', label: 'Teamwork' },
    { value: 'Time Management', label: 'Time Management' },
    { value: 'Problem Solving', label: 'Problem Solving' },
    { value: 'Creativity', label: 'Creativity' },
    { value: 'Critical Thinking', label: 'Critical Thinking' },
    { value: 'Decision Making', label: 'Decision Making' },
    { value: 'Adaptability', label: 'Adaptability' },
    { value: 'Conflict Resolution', label: 'Conflict Resolution' },
    { value: 'Interpersonal Skills', label: 'Interpersonal Skills' },
    { value: 'Organizational Skills', label: 'Organizational Skills' },
    { value: 'Research', label: 'Research' },
    { value: 'Writing', label: 'Writing' },
    { value: 'Presentation Skills', label: 'Presentation Skills' },
    { value: 'Public Speaking', label: 'Public Speaking' },
    { value: 'Negotiation', label: 'Negotiation' },
    { value: 'Sales', label: 'Sales' },
    { value: 'Marketing', label: 'Marketing' },
    { value: 'Data Analysis', label: 'Data Analysis' },
    { value: 'Statistics', label: 'Statistics' },
    { value: 'Programming', label: 'Programming' },
    { value: 'Web Development', label: 'Web Development' },
    { value: 'Database Management', label: 'Database Management' },
    { value: 'Data Science', label: 'Data Science' },
    { value: 'Machine Learning', label: 'Machine Learning' },
    { value: 'Artificial Intelligence', label: 'Artificial Intelligence' },
    { value: 'Cybersecurity', label: 'Cybersecurity' },
    { value: 'Information Technology', label: 'Information Technology' },
    { value: 'Network Administration', label: 'Network Administration' },
    { value: 'Graphic Design', label: 'Graphic Design' },
    { value: 'UI/UX Design', label: 'UI/UX Design' },
    { value: 'Video Production', label: 'Video Production' },
    { value: 'Photography', label: 'Photography' },
    { value: 'Animation', label: 'Animation' },
    { value: 'Game Design', label: 'Game Design' },
    { value: '3D Modeling', label: '3D Modeling' },
    { value: 'Music Production', label: 'Music Production' },
    { value: 'Sound Design', label: 'Sound Design' },
    { value: 'Project Management', label: 'Project Management' },
    { value: 'Financial Analysis', label: 'Financial Analysis' },
    { value: 'Accounting', label: 'Accounting' },
    { value: 'Economics', label: 'Economics' },
    { value: 'Business Strategy', label: 'Business Strategy' },
    { value: 'Entrepreneurship', label: 'Entrepreneurship' },
    { value: 'Human Resources', label: 'Human Resources' },
    { value: 'Customer Service', label: 'Customer Service' }
];
  